kcl-lang/kpm

- pkg/mod/modfile.go
- pkg/mod/modfile_test.go
- pkg/package/package.go
fix issue #98 
kpm add
If the `kpm add` command does not contain the tag information, the path where the package is saved loses the tag information.
```release-note
None
```
> fix: fix the localpath when 'kpm add' from oci registry without tag.

- kpm.go
- pkg/cmd/cmd_add.go
- pkg/cmd/cmd_pull.go
- pkg/cmd/cmd_push.go
- pkg/cmd/cmd_run.go
- pkg/errors/errors.go
- pkg/mod/modfile.go
- pkg/oci/oci.go
- pkg/opt/opt.go
- pkg/reporter/reporter.go
- pkg/settings/settings.go
- pkg/settings/settings_test.go
- pkg/utils/utils.go
- test/e2e/kpm_test.go
- test/e2e/test_suites/kpm/no_args/kpm_pull_with_no_args/test_suite.stderr
- test/e2e/test_suites/kpm/no_args/kpm_pull_with_only_tag/test_suite.stderr
- test/e2e/test_suites/kpm/no_args/kpm_pull_with_pkg_name/test_suite.stderr
- test/e2e/test_suites/kpm/no_args/kpm_pull_with_pkg_name/test_suite.stdout
- test/e2e/test_suites/kpm/no_args/kpm_pull_with_pkg_name_tag/test_suite.stderr
- test/e2e/test_suites/kpm/no_args/kpm_pull_with_pkg_name_tag/test_suite.stdout
- test/e2e/test_suites/kpm/no_args/run_oci_with_invalid_ref/test_suite.stderr
- test/e2e/test_suites/kpm/no_args/run_oci_with_invalid_ref/test_suite.stdout
- test/e2e/test_suites/kpm/no_args/run_oci_with_invalid_url/test_suite.stderr
- test/e2e/test_suites/kpm/no_args/run_oci_with_invalid_url_without_tag/test_suite.stderr
- test/e2e/test_suites/kpm/run_pkg_not_tar/kpm_push_with_invalid_url/test_suite.stderr
- test/e2e/test_suites/kpm/run_tar/kpm_push_with_invalid_url/test_suite.stderr
- test/e2e/test_suites/kpm/run_tar/run_tar_with_exist_not_tar/test_suite.stderr
fix issue #128 
pkg/cmd/cmd_pull.go
pkg/reporter/reporter.go
> feat: make 'kpm pull' diagnostics feel better.

- pkg/errors/errors.go
- pkg/oci/oci.go
- pkg/package/test_data/test_data_add_deps/main.k
- pkg/package/test_data/test_init_empty_mod/main.k
- pkg/reporter/reporter.go
- pkg/settings/settings.go
- pkg/settings/settings_test.go
- pkg/settings/test_data/expected.json
…try under http protocol
fix issue https://github.com/kcl-lang/kpm/issues/139
pkg/settings/settings.go
> feat: added env 'OCI_REG_PLAIN_HTTP' as a switch to support OCI Registry under http protocol

- pkg/version/version.go
- pkg/version/version_test.go
> chore: bump kpm version from 0.3.2 to 0.3.3.

- pkg/cmd/cmd_pkg.go
- pkg/cmd/cmd_push.go
- pkg/package/modfile.go
- pkg/package/package.go
- pkg/package/package_test.go
- pkg/package/test_data/test_pkg_with_vendor/kcl2/kcl.mod
- pkg/package/test_data/test_pkg_with_vendor/kcl2/main.k
fix issue #151 
pkg/package/package.go
> feat: add '--vendor' to control whether all the dependencies are packaged together.

- pkg/api/kpm_pkg.go
- pkg/api/kpm_pkg_test.go
- pkg/api/test_data/test_kpm_package/kcl_pkg/main.k
- pkg/api/test_data/test_kpm_package/kcl_pkg/sub/sub1/main.k
- pkg/api/test_data/test_kpm_package/kcl_pkg/sub/sub1/main2.k
fix issue #158 #159 
pkg/api/kpm_pkg.go
> feat: add the real path for all the schema type.

- pkg/api/kpm_pkg.go
- pkg/api/kpm_pkg_test.go
- pkg/api/test_data/test_kpm_package/no_kcl_files/kcl.mod
- pkg/api/test_data/test_kpm_package/no_kcl_files/main.k
- pkg/errors/errors.go
> fix: fix the 'No kcl files' error in api.

- pkg/api/kpm_run.go
- pkg/api/kpm_run_test.go
- pkg/api/test_data/test_run_pkg_in_path/expected.json
- pkg/api/test_data/test_run_tar_in_path/expected.json
- pkg/package/test_data/test_data_add_deps/kcl.mod
> feat: add more apis for 'kpm run' to get the full compile results

- pkg/opt/opt.go
- pkg/opt/opt_test.go
> feat: add entry set APIs

- README-zh.md
- README.md
- docs/publish_pkg_to_ah-zh.md
- docs/publish_pkg_to_ah.md
Fixed #204  
docs/publish_pkg_to_ah-zh.md
> doc: add docs for 'publish kcl package'

- pkg/client/client.go
Fixed KCL issue https://github.com/kcl-lang/kcl/issues/891
Fixed KCL issue https://github.com/kcl-lang/kcl/issues/823
pkg/client/client.go
> feat: create a symbolic link for the dependencies

- pkg/api/kpm_run.go
- pkg/api/kpm_run_test.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/cmd/cmd_import.go
- pkg/cmd/cmd_init.go
- pkg/cmd/cmd_metadata.go
- pkg/cmd/cmd_pkg.go
- pkg/cmd/cmd_push.go
- pkg/cmd/cmd_update.go
- pkg/oci/oci.go
- pkg/oci/oci_test.go
- pkg/package/package.go
- pkg/reporter/reporter.go
- pkg/runner/entry.go
- pkg/settings/settings.go
- pkg/utils/utils.go
- test/e2e/test_suites/kpm/exec_inside_pkg/add_path_not_exist/test_suite.stderr
- test/e2e/test_suites/kpm/exec_outside_pkg/add_exist_not_pkgpath/test_suite.stderr
- test/e2e/test_suites/kpm/exec_outside_pkg/add_path_not_exist/test_suite.stderr
- test/e2e/test_suites/kpm/exec_outside_pkg/add_with_name_outside/test_suite.stderr
- test/e2e/test_suites/kpm/exec_outside_pkg/add_with_name_tag_outside/test_suite.stderr
- test/e2e/test_suites/kpm/exec_outside_pkg/add_with_no_args_outside/test_suite.stderr
- test/e2e/test_suites/kpm/exec_outside_pkg/login_reg_without_username/test_suite.stderr
- test/e2e/test_suites/kpm/exec_outside_pkg/logout_reg_with_invalid_reg/test_suite.stderr
- test/e2e/test_suites/kpm/exec_outside_pkg/run_tar_with_noargs_input/test_suite.stderr
- test/e2e/test_suites/kpm/exec_outside_pkg/run_with_no_args/test_suite.stderr
> fix: throw all errors from low level

- go.mod
- go.sum
- pkg/api/kpm_pkg.go
- pkg/api/kpm_pkg_test.go
- pkg/api/test_data/test_kpm_package/get_schema_ty/aaa/kcl.mod
- pkg/api/test_data/test_kpm_package/get_schema_ty/aaa/kcl.mod.lock
- pkg/api/test_data/test_kpm_package/get_schema_ty/aaa/main.k
- pkg/api/test_data/test_kpm_package/get_schema_ty/bbb/kcl.mod
- pkg/api/test_data/test_kpm_package/get_schema_ty/bbb/main.k
- pkg/constants/constants.go
Fixes https://github.com/kcl-lang/kcl/issues/891
> feat: add api to 'GetFullSchemaTypeMappingWithFilters'

- pkg/client/client_test.go
> fix: fix ci

- pkg/api/kpm_run.go
- pkg/api/kpm_run_test.go
- pkg/opt/opt.go
> feat: add api whose input option with style 'WithXXX'

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/opt/opt.go
- pkg/opt/opt_test.go
> feat: optimize api 'RunWithOpts' and disable some output with '--no_sum_check'

- pkg/api/kpm_run_test.go
- pkg/api/test_data/test_run_pkg_in_path/test_run_no_sum_check/kcl.mod
- pkg/api/test_data/test_run_pkg_in_path/test_run_no_sum_check/main.k
- pkg/client/client.go
> fix: fix the module not found when run with '--no_sum_check'

- pkg/api/kpm_pkg.go
- pkg/api/kpm_pkg_test.go
- pkg/api/test_data/test_get_entries/no_entries/kcl.mod
- pkg/api/test_data/test_get_entries/no_entries/main.k
- pkg/api/test_data/test_get_entries/with_path_entries/kcl.mod
- pkg/api/test_data/test_get_entries/with_path_entries/sub/sub.k
- pkg/package/modfile.go
- pkg/package/package.go
Fixed #228 
Defensive programming has been added to api 'GetEntries()' to reduce NPE
> fix: defensive programming has been added to api 'GetEntries()' to reduce NPE

- aaa/kcl.mod
- aaa/main.k
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/test_data/test_add_diff_version/no_sum_check/kcl.mod.bak
- pkg/client/test_data/test_add_diff_version/no_sum_check/kcl.mod.expect
- pkg/client/test_data/test_add_diff_version/no_sum_check/main.k
- pkg/client/test_data/test_add_diff_version/with_sum_check/kcl.mod.bak
- pkg/client/test_data/test_add_diff_version/with_sum_check/kcl.mod.expect
- pkg/client/test_data/test_add_diff_version/with_sum_check/kcl.mod.lock.bak
- pkg/client/test_data/test_add_diff_version/with_sum_check/kcl.mod.lock.expect
- pkg/client/test_data/test_add_diff_version/with_sum_check/main.k
> fix: fix the npe when 'kpm add'

- README.md
> corrected the version command

- pkg/api/kpm_run.go
- pkg/api/kpm_run_test.go
- pkg/api/test_data/test_run_pkg_in_path/test_run_with_no_log/kcl.mod
- pkg/api/test_data/test_run_pkg_in_path/test_run_with_no_log/main.k
- pkg/opt/opt.go
- pkg/opt/opt_test.go
> feat: add 'WithLogWriter' for api 'RunWithOpts'

- README-zh.md
- README.md
- pkg/cmd/cmd_add.go
- pkg/cmd/cmd_flags.go
- pkg/cmd/cmd_import.go
- pkg/cmd/cmd_init.go
- pkg/cmd/cmd_login.go
- pkg/cmd/cmd_logout.go
- pkg/cmd/cmd_metadata.go
- pkg/cmd/cmd_pkg.go
- pkg/cmd/cmd_pull.go
- pkg/cmd/cmd_push.go
- pkg/cmd/cmd_push_test.go
- pkg/cmd/cmd_run.go
- pkg/cmd/cmd_update.go
- pkg/version/version.go
- pkg/version/version_test.go
> chore: make the kpm cli deprecated

- go.mod
- go.sum
- kpm.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/test_data/test_dependency_graph/kcl.mod
- pkg/cmd/cmd_graph.go
- pkg/graph/graph.go
- test/e2e/test_suites/kpm/exec_outside_pkg/help_msg/test_suite.stdout
solves: #263 
kpm.go
pkg/cmd/cmd_graph.go
pkg/client.go
> feat: add graph subcommand to print dependency graph

- README.md
> Added contribution guideline link in README

- pkg/package/toml.go
typo fix in `pkg/package/toml.go` from GTI to GIT
cc @Peefy
> typo fix in toml.go

- pkg/client/client.go
- pkg/opt/opt.go
- pkg/path/path_test.go
- pkg/path/path_unix.go
- pkg/path/path_windows.go
re https://github.com/crossplane-contrib/function-kcl/issues/43
> feat: Added some methods for sanitizing path on different platforms

- pkg/api/kpm_run.go
- pkg/client/client.go
- pkg/opt/opt.go
re https://github.com/crossplane-contrib/function-kcl/issues/43
> fix: fix windows path bug

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/test_data/test_run_oci_with_settings/kcl.yaml
+ fix: oci source with settings files
+ pkg/client/client.go
+ pkg/client/client_test.go
> fix: oci source with settings files

- pkg/client/client.go
- pkg/client/test_data/add_with_local_path/expect/pkg/kcl.mod.lock
- pkg/utils/test_data/test_link/is_link_exist/link_target_not_exist
- pkg/utils/test_data/test_link/is_link_exist/test.txt
- pkg/utils/utils.go
- pkg/utils/utils_test.go
> fix: rm checksum for dependencies from local path and fix symlink

- pkg/api/kpm_run.go
- pkg/api/kpm_run_test.go
+ fix: entry override settings file
> fix: entry override settings file

- pkg/client/client.go
- pkg/package/modfile.go
- pkg/package/package.go
- pkg/package/test_data/test_data_toml/expected.toml
- pkg/package/toml.go
- pkg/package/toml_test.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
> add kpm pkg include and exclude

- pkg/client/client.go
- pkg/cmd/cmd_add.go
- pkg/opt/opt.go
- pkg/package/modfile.go
> added rename flag in kpm add

- research/design-doc/sparse_checkout_asishkumar.md
>  added design doc for sparse checkout

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/test_data/resolve_metadata/with_package/kcl.mod
- pkg/client/test_data/resolve_metadata/with_package/kcl.mod.lock
- pkg/client/test_data/test_mod_file_package/test_pkg/expect.mod.lock
- pkg/client/test_data/test_mod_file_package/test_pkg_win/expect.mod.lock
- pkg/client/test_data/test_run_git_package/kcl.mod
- pkg/client/test_data/test_run_git_package/main.k
- pkg/package/modfile.go
- pkg/package/modfile_test.go
- pkg/package/package.go
> Rename fullname to reponame

- pkg/api/kpm_pkg_test.go
- pkg/api/test_data/test_kpm_package/kcl_pkg/kcl.mod.lock
- pkg/client/client.go
- pkg/downloader/source.go
- pkg/package/modfile.go
- pkg/package/package.go
- pkg/package/package_test.go
- pkg/package/toml.go
re https://github.com/kcl-lang/kpm/pull/478
> refactor: refactor load package

- pkg/checker/checker.go
- pkg/checker/checker_test.go
- pkg/mock/oci_env_mock.go
- pkg/mock/test_data/kcl.mod
- pkg/mock/test_data/kcl.mod.lock
- pkg/mock/test_data/main.k
- pkg/mock/test_script/cleanup_test_environment.sh
- pkg/mock/test_script/push_pkg.sh
- pkg/settings/settings.go
re https://github.com/kcl-lang/kpm/issues/394
kcl-lang/kpm/pkg/checker
This PR contains an isolated implementation of the checker module to validate KPM third-party dependencies. The changes have not yet been integrated with KPM third-party dependencies; integration will be done in the future once the checker module design is finalised. The PR includes:
- `SumChecker`, which validates the dependency checksums in kclPkg.
- `getTrustedSum`, which gives the trusted sum of the dependency from OCI manifest
> Added trustedSum in checker module

- pkg/client/add_test.go
- pkg/client/client_test.go
- pkg/client/graph_test.go
- pkg/client/test.go
- pkg/client/test_data/add_with_mod_spec/git_mod_0/kcl.mod.bk
- pkg/client/test_data/add_with_mod_spec/git_mod_0/kcl.mod.expect
- pkg/client/test_data/add_with_mod_spec/git_mod_0/kcl.mod.lock.expect
- pkg/client/test_data/add_with_mod_spec/git_mod_0/main.k
- pkg/client/test_data/add_with_mod_spec/git_mod_1/kcl.mod.bk
- pkg/client/test_data/add_with_mod_spec/git_mod_1/kcl.mod.expect
- pkg/client/test_data/add_with_mod_spec/git_mod_1/kcl.mod.lock.expect
- pkg/client/test_data/add_with_mod_spec/git_mod_1/main.k
- pkg/downloader/downloader.go
- pkg/package/modfile.go
- pkg/package/test_data/test_rename_pkg/kcl.mod.lock
- pkg/visitor/visitor.go
> fix: fix redownload when the remote repo has no mod file

- pkg/client/client_test.go
- pkg/client/deperated_test.go
- pkg/client/run_test.go
- pkg/downloader/downloader.go
- pkg/features/features.go
> fix: fixed an issue where dependencies could not be downloaded under the new storage structure

- pkg/client/client_test.go
- pkg/client/test_data/add_with_mod_spec/empty_version/kcl.mod.lock.expect
- pkg/client/test_data/add_with_mod_spec/no_oci_ref/kcl.mod.lock.expect
- pkg/client/test_data/add_with_mod_spec/no_spec/kcl.mod.lock.expect
- pkg/client/test_data/add_with_mod_spec/oci/kcl.mod.lock.expect
- pkg/client/test_data/add_with_mod_spec/rename_no_spec/kcl.mod.lock.expect
- pkg/client/test_data/add_with_mod_spec/rename_spec_only/kcl.mod.lock.expect
- pkg/client/test_data/add_with_mod_spec/spec_only/kcl.mod.lock.expect
- pkg/client/test_data/add_with_mod_spec/spec_only_no_ver/kcl.mod.lock.expect
- pkg/client/test_data/test_data_add_deps/kcl.mod.lock
- pkg/client/test_data/test_update/test_update_kcl_mod/expected
- pkg/client/test_data/test_update/test_update_kcl_mod/kcl.mod.lock
- pkg/client/test_data/test_update/test_update_kcl_mod_lock/kcl.mod.lock
- pkg/client/test_data/test_update_with_mvs/update_0/dep_0/kcl.mod.lock
- pkg/client/test_data/test_update_with_mvs/update_0/dep_1/kcl.mod.lock
- pkg/client/test_data/test_update_with_mvs/update_0/dep_2/kcl.mod.lock
- pkg/client/test_data/test_update_with_mvs/update_0/pkg/kcl.mod.lock
- pkg/client/test_data/test_update_with_mvs/update_1/dep_0/kcl.mod.lock
- pkg/client/test_data/test_update_with_mvs/update_1/dep_1/kcl.mod.lock
- pkg/client/test_data/test_update_with_mvs/update_1/dep_2/kcl.mod.lock
- pkg/client/test_data/test_update_with_mvs/update_1/pkg/kcl.mod.lock
- pkg/client/update.go
> fix: fill the missing checksum in kcl.mod.lock in api Update

- pkg/client/client_test.go
- pkg/client/pull_test.go
- pkg/client/run.go
- pkg/client/run_test.go
- pkg/client/test_data/test_run_hyphen_entries/kcl.mod
- pkg/client/test_data/test_run_hyphen_entries/kcl.mod.lock
- pkg/client/test_data/test_run_hyphen_entries/main.k
- pkg/client/test_data/test_run_hyphen_entries/stdout
- pkg/utils/utils.go
> fix: replace all the hyphen to underscore in ModRelativePath

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/features/features.go
- test/e2e/test_suites/kpm/exec_outside_pkg/kpm_pull_with_oci_url/test_suite.stdout
- test/e2e/test_suites/kpm/exec_outside_pkg/kpm_pull_with_pkg_name/test_suite.stdout
- test/e2e/test_suites/kpm/exec_outside_pkg/pull_private_pkg/test_suite.stdout
fix #394 
pkg/client/client.go
This PR adds a checksum verification step to the `kpm` workflow to enhance the security and integrity of third-party dependencies. The integration ensures that each package’s checksum is validated during downloading, preventing unauthorized or tampered packages from being incorporated into the project.
> feat: add checksum in kpm workflow

- docs/proposal/kcl-checksum-integration-code-design.md
- docs/proposal/kcl-checksum-integration-design.md
- docs/proposal/kcl-checksum-verification-checker-module-design.md
- docs/proposal/kcl-checksum-verification-proposal.md
> [PreTest] Technical proposal for the checksum check of the three-party dependencies

- pkg/checker/checker.go
- pkg/checker/checker_test.go
- pkg/client/check.go
- pkg/client/check_test.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/deperated.go
- pkg/client/test_data/test_mod_check/name_failed/kcl.mod
- pkg/client/test_data/test_mod_check/name_failed/kcl.mod.lock
- pkg/client/test_data/test_mod_check/name_failed/main.k
- pkg/client/test_data/test_mod_check/pass/kcl.mod
- pkg/client/test_data/test_mod_check/pass/kcl.mod.lock
- pkg/client/test_data/test_mod_check/pass/main.k
- pkg/client/test_data/test_mod_check/sum/kcl.mod
- pkg/client/test_data/test_mod_check/sum/kcl.mod.lock
- pkg/client/test_data/test_mod_check/sum/main.k
- pkg/client/test_data/test_mod_check/version_failed/kcl.mod
- pkg/client/test_data/test_mod_check/version_failed/kcl.mod.lock
- pkg/client/test_data/test_mod_check/version_failed/main.k
- pkg/client/update.go
- pkg/features/features.go
> feat: add API for checker and support mod checking in update

- pkg/checker/checker_test.go
- pkg/client/client_test.go
- pkg/client/deperated.go
- pkg/client/issues_test.go
- pkg/client/push.go
- pkg/client/push_test.go
- pkg/client/test_data/issues/github.com/kcl-lang/kcl/issues/1768/README.md
- pkg/client/test_data/issues/github.com/kcl-lang/kcl/issues/1768/depends_on_pushed_mod/kcl.mod.bk
- pkg/client/test_data/issues/github.com/kcl-lang/kcl/issues/1768/depends_on_pushed_mod/kcl.mod.expect
- pkg/client/test_data/issues/github.com/kcl-lang/kcl/issues/1768/depends_on_pushed_mod/kcl.mod.lock.expect
- pkg/client/test_data/issues/github.com/kcl-lang/kcl/issues/1768/depends_on_pushed_mod/main.k
- pkg/client/test_data/issues/github.com/kcl-lang/kcl/issues/1768/pushed_mod/kcl.mod
- pkg/client/test_data/issues/github.com/kcl-lang/kcl/issues/1768/pushed_mod/main.k
- pkg/client/test_data/test_push/push_0/kcl.mod
- pkg/client/test_data/test_push/push_0/main.k
- pkg/client/test_data/test_push/test_pushed_mod/kcl.mod
- pkg/client/test_data/test_push/test_pushed_mod/kcl.mod.lock
- pkg/client/test_data/test_push/test_pushed_mod/main.k
- pkg/cmd/cmd_push.go
- pkg/mock/test_script/push_pkg.sh
- pkg/opt/opt.go
- pkg/utils/utils.go
- pkg/utils/utils_test.go
- test/e2e/test_suites/kpm/exec_outside_pkg/kpm_pull_with_oci_url/test_suite.stdout
- test/e2e/test_suites/kpm/exec_outside_pkg/kpm_pull_with_oci_url_tag/test_suite.stdout
- test/e2e/test_suites/kpm/exec_outside_pkg/pull_private_pkg/test_suite.stdout
- test/e2e/test_suites/kpm/exec_outside_pkg/run_oci_with_invalid_url/test_suite.stderr
- test/e2e/test_suites/kpm/exec_outside_pkg/run_oci_with_invalid_url_without_tag/test_suite.stderr
re https://github.com/kcl-lang/kcl/issues/1768
> fix: fix missing tag in command push

- pkg/client/client_test.go
- pkg/client/test_data/test_metadata_offline/ugly.kcl.mod
- pkg/client/test_data/test_no_download_with_metadata_offline/kcl.mod
- pkg/client/test_data/test_no_download_with_metadata_offline/kcl.mod.lock
- pkg/client/test_data/test_no_download_with_metadata_offline/main.k
- pkg/client/update.go
- pkg/downloader/downloader.go
- pkg/resolver/resolver.go
- pkg/visitor/visitor.go
Remove the auto-updating for kcl.mod when using command metadata.
> fix: Remove the auto-updating for kcl.mod when using command metadata.

- pkg/api/kpm_run.go
- pkg/api/kpm_run_test.go
- pkg/client/client_test.go
- pkg/client/metadata.go
- pkg/client/test_data/test_run_with_modspec_version/kcl.mod.expect
- pkg/client/update.go
- pkg/package/package.go
add a switch to control the auto-updating for mod file
> feat: add a switch to control the auto-updating for mod file

- pkg/client/issues_test.go
- pkg/client/test_data/issues/github.com/kcl-lang/kcl/issues/1788/README.md
- pkg/client/test_data/issues/github.com/kcl-lang/kcl/issues/1788/mod/main.k
re https://github.com/kcl-lang/kcl/issues/1788
> test: add a test case for kcl issue 1788

- pkg/client/run_test.go
- pkg/client/test_data/test_add_git_dep/kcl.mod
- pkg/client/test_data/test_add_git_dep/kcl.mod.lock
- pkg/client/test_data/test_add_git_dep/main.k
- pkg/downloader/downloader.go
- pkg/downloader/source.go
> fix: fix failure when add git repo as dependency by protocol 'git://'

- pkg/api/kpm_env_test.go
> Lfx Pretest : Improve test coverage by 90 percent. 
