pkg/cmd/cmd_add.go
pkg/cmd/cmd_pkg.go
pkg/cmd/cmd_run.go
pkg/utils/utils.go
pkg/utils/utils_test.go

fix issue #27 .
kpm/pkg/utils.go
Relative paths can cause problems with paths not being found, so change the file path read from KPM_HOME to an absolute path.
```release-note
None
```

fix: Change the path read from env KPM_HOME to an absolute path.

---

README-zh.md
README.md

feat: make README better.

---

pkg/utils/utils.go
pkg/utils/utils_test.go

kpm/pkg/utils/utils.go
```release-note
None
```

feat: add default KPM_HOME in 'user_root/.kpm'

---

README-zh.md
README.md

README
```release-note
None
```

feat: add how to set env in README.

---

README-zh.md
README.md
pkg/cmd/cmd_add.go
pkg/cmd/cmd_init.go
pkg/cmd/cmd_pkg.go
pkg/cmd/cmd_run.go
pkg/errors/errors.go
pkg/package/package.go
pkg/package/package_test.go
pkg/runner/runner.go
pkg/runner/runner_test.go

feat: add kclvm_cli check and KPM_HOME check.

---

go.mod
go.sum
pkg/cmd/cmd_add.go
pkg/cmd/cmd_init.go
pkg/cmd/cmd_pkg.go
pkg/cmd/cmd_run.go
pkg/env/env.go
pkg/env/env_test.go
pkg/errors/errors.go
pkg/mod/modfile.go
pkg/package/package.go
pkg/package/package_test.go
pkg/utils/utils.go
pkg/utils/utils_test.go

fix #48  
kpm/pkg/env
rename KPM_HOME to KCL_PKG_PATH
```release-note
None
```

feat: rename KPM_HOME to KCL_PKG_PATH

---

pkg/mod/modfile.go

fix #59 
kpm add
create a symbolic link for the dependencies.
```release-note
None
```

feat: create a symbolic link for the dependencies.

---

kpm.go
pkg/cmd/cmd_metadata.go
pkg/mod/modfile.go
pkg/package/package.go
pkg/package/package_test.go
pkg/package/test_data/resolve_metadata/kcl.mod
pkg/package/test_data/resolve_metadata/kcl.mod.lock

issue #66 
kpm/pkg/package.go
support 'kpm metadata' to show the metadata for dependencies.
```release-note
None
```

feat: support 'kpm metadata' to show the metadata for dependencies.

---

pkg/cmd/cmd_flags.go
pkg/cmd/cmd_metadata.go
pkg/package/package.go
pkg/package/package_test.go

fix #71 
kpm metadata
```release-note
None
```

feat: add '--update' to 'kpm metadata' to control whether to automatically update missing packages

---

pkg/oci/oci.go

fix a typo.
```release-note
None
```

fix: rm a panic.

---

pkg/settings/settings.go
pkg/settings/settings_test.go
pkg/settings/test_data/expected.json

'KusionStack' -> 'kusionstack'
```release-note
None
```

fix: fix default repo.

---

pkg/mod/test_data/test_data_toml/expected_reversed.toml
pkg/mod/toml_test.go

test case
```release-note
None
```

fix: Fixed the occasional failure in the test cases.

---

go.mod
go.sum
pkg/cmd/cmd_add.go
pkg/errors/errors.go
pkg/mod/modfile.go
pkg/oci/oci.go
pkg/opt/opt.go
pkg/semver/semver.go
pkg/semver/semver_test.go
test/e2e/test_suites/kpm/no_args/run_oci_with_invalid_url_without_tag/test_suite.stderr
test/e2e/test_suites/kpm/run_tar/run_tar_with_exist_not_tar/test_suite.stderr
test/e2e/test_suites/kpm/workflows/add_multi_times/2.first_add_konfig_dep/test_suite.stderr

issue #74 
kpm add
When the user uses the `kpm add`, if no tag is provided, `kpm` will first ask the oci registry to obtain all the tags, then calculate the latest `tag` according to the semantic version, and download the package with the latest tag.
```release-note
None
```

feat: 'kpm add' will download the latest version by default.

---

.goreleaser.yml
kpm.go
makefile
pkg/version/version.go
pkg/version/version_test.go
scripts/e2e.sh

fix issue #82 
kpm version.
```release-note
None
```

feat: If kpm can not find the version in the build flags, it will return the version constant.

---

pkg/mod/toml_test.go

unit test
```release-note
None
```

feat: add some prints in test case 'TestMarshalTOML' to show more test info.

---

pkg/mod/modfile.go
pkg/mod/modfile_test.go

fix issue #97 
kpm add.
After untaring kcl package tar, the tar file should be deleted.
```release-note
None
```

fix: After untaring kcl package tar, the tar file should be deleted.

---

pkg/package/package.go

fix issue #97 
kpm add.
'd.LocalFullPath' is empty, because it can not be loaded from kcl.mod.
```release-note
None
```

fix: fix a mistakes in package path.

---

pkg/version/version.go
pkg/version/version_test.go

bump kpm version to 0.2.4.
bump kpm version to 0.2.4.
```release-note
None
```

chore: bump kpm version to 0.2.4.

---

pkg/opt/opt.go
pkg/opt/opt_test.go

kpm run
```release-note
None
```

fix: fix '--tag' is invalid in `kpm run`.

---

.github/workflows/cla.yml
README-zh.md
README.md
docs/publish_your_kcl_packages-zh.md
docs/publish_your_kcl_packages.md

docs: make some docs better.

---

go.mod
go.sum

chore: bump kcl version from v0.5.0-alpha.4 to v0.5.0-beta.1.

---

pkg/version/version.go
pkg/version/version_test.go

chore: bump kpm version from '0.2.4' to '0.2.5'.

---

.goreleaser.yml

feat: specify the GOOS/GOARCH to build in '.goreleaser.yml'.

---

pkg/version/version.go
pkg/version/version_test.go

feat: bump kpm version from 0.2.5 to 0.2.6.

---

go.mod
go.sum
pkg/mod/modfile.go
pkg/package/package.go
pkg/runner/args.go
pkg/runner/runner.go
pkg/runner/runner_test.go
pkg/version/version.go
pkg/version/version_test.go

feat: bump kpm version from 0.2.5 to 0.3.0.

---

pkg/cmd/cmd_add.go
pkg/mod/modfile.go
pkg/package/package.go
pkg/settings/settings.go
pkg/settings/settings_test.go

fix: lock on global file package-cache when 'kpm add'.

---

README-zh.md
README.md
docs/command-reference-zh/2.add.md
docs/command-reference/2.add.md
docs/kpm_oci-zh.md
docs/kpm_oci.md
makefile
pkg/cmd/cmd_push.go
pkg/cmd/cmd_push_test.go
pkg/mod/modfile_test.go
pkg/package/test_data/expected/kcl.mod.reverse.lock
pkg/package/test_data/expected/kcl.reverse.mod
pkg/settings/settings.go
pkg/settings/settings_test.go
pkg/settings/test_data/expected.json
test/e2e/test_suites/kpm/no_args/kpm_pull_with_pkg_name/test_suite.stdout
test/e2e/test_suites/kpm/no_args/kpm_pull_with_pkg_name_tag/test_suite.input
test/e2e/test_suites/kpm/no_args/kpm_pull_with_pkg_name_tag/test_suite.stdout

fix https://github.com/kcl-lang/kpm/issues/136

feat: replace the default registry from 'ghcr.io/kusionstack' to 'ghcr.io/kcl-lang'.

---

pkg/version/version.go
pkg/version/version_test.go

chore: bump kpm version from 0.3.1 to 0.3.2.

---

.gitignore
scripts/e2e.sh
scripts/e2e_prepare.sh
scripts/pull_pkg.sh
scripts/push_pkg.sh
scripts/reg.sh
scripts/registry_auth/htpasswd
test/e2e/test_suites/kpm/no_args/kpm_pull_with_oci_url/test_suite.input
test/e2e/test_suites/kpm/no_args/kpm_pull_with_oci_url/test_suite.stdout
test/e2e/test_suites/kpm/no_args/kpm_pull_with_oci_url_tag/test_suite.input
test/e2e/test_suites/kpm/no_args/kpm_pull_with_oci_url_tag/test_suite.stdout
test/e2e/test_suites/kpm/no_args/kpm_pull_with_pkg_name/test_suite.stdout
test/e2e/test_suites/kpm/no_args/kpm_pull_with_pkg_name_tag/test_suite.stdout
test/e2e/test_suites/kpm/no_args/run_oci_with_invalid_ref/test_suite.stderr
test/e2e/test_suites/kpm/no_args/run_oci_with_invalid_ref/test_suite.stdout
test/e2e/test_suites/kpm/run_tar/run_tar_with_exist_not_tar/test_suite.stderr

fix issue https://github.com/kcl-lang/kpm/issues/141.
kpm e2e test

feat: add an oci registry for e2e test.

---

README-zh.md
README.md
docs/publish_to_docker_reg-zh.md
docs/publish_to_docker_reg.md

docs for `kpm push` to docker.io

docs: add guide docs for 'kpm push' to docker.io.

---

pkg/api/kpm_env.go
pkg/api/kpm_pkg.go
pkg/api/kpm_pkg_test.go
pkg/api/test_data/test_kpm_package/kcl_pkg/kcl.mod
pkg/api/test_data/test_kpm_package/kcl_pkg/kcl.mod.lock
pkg/api/test_data/test_kpm_package/kcl_pkg/main.k
pkg/api/test_data/test_kpm_package/kcl_pkg/sub/main.k
pkg/package/package.go

fix #155 
pkg/api/kpm_pkg.go
add api for kcl package info.

feat: add api for get kcl package info.

---

pkg/api/kpm_pkg.go
pkg/api/kpm_pkg_test.go

feat: support filter for api to get schema type.

---

go.mod
go.sum

chore: bump kcl version from 0.5.4 to 0.5.6

---

pkg/api/kpm_run.go
pkg/api/kpm_run_test.go
pkg/api/test_data/test_work_dir/base/base.k
pkg/api/test_data/test_work_dir/dev/kcl.mod
pkg/api/test_data/test_work_dir/dev/main.k
test/e2e/kpm_test.go
test/e2e/test_suites/kpm/kpm_run/test_kpm_run_with_local_dep/test_suite.input

fix: set the 'kcl.mod' path as workdir

---

pkg/version/version.go
pkg/version/version_test.go

chore: bump kpm version from '0.3.4' to '0.3.5'

---

pkg/opt/opt.go
pkg/opt/opt_test.go

feat: take 'Workdir' as package path for api

---

go.mod
go.sum

chore: bump kcl version from 0.5.6 to 0.6.0-alpha.1

---

pkg/version/version.go
pkg/version/version_test.go

feat: bump kpm version from 0.3.5 to 0.3.6

---

pkg/client/client_test.go

fix: bump the latest version of k8s in test case

---

pkg/client/client.go
pkg/oci/oci.go
pkg/opt/opt.go
scripts/pkg_in_reg/kcl1/kcl.mod
scripts/pkg_in_reg/kcl2/kcl.mod
test/e2e/kpm_test.go

fixed #203 
pkg/client/client.go
pkg/oci/oci.go
add method `FetchManifestIntoJsonStr` to `KpmClient` to fetch the oci manifest of a package.

feat: Add a method to KpmClient to fetch the oci manifest

---

go.mod
go.sum
pkg/version/version.go
pkg/version/version_test.go

chore: bump kpm version from 0.3.6 to 0.3.7

---

pkg/client/client.go
pkg/client/client_test.go
pkg/client/test_data/test_metadata_offline/beautiful.kcl.mod
pkg/client/test_data/test_metadata_offline/main.k
pkg/client/test_data/test_metadata_offline/ugly.kcl.mod
pkg/cmd/cmd_metadata.go

pkg/client/client.go
fix: remove the autoupdate of kcl.mod when use 'kpm metadata'

fix: remove the autoupdate of kcl.mod when use 'kpm metadata'

---

pkg/api/kpm_run.go
pkg/api/kpm_run_test.go
pkg/api/test_data/test_run_with_nosumcheck/kcl.mod
pkg/api/test_data/test_run_with_nosumcheck/main.k
pkg/client/client.go
pkg/client/client_test.go
pkg/client/test_data/test_add_no_sum_check/kcl.mod.bak
pkg/client/test_data/test_add_no_sum_check/main.k
pkg/client/test_data/test_run_no_sum_check/kcl.mod
pkg/client/test_data/test_run_no_sum_check/main.k
pkg/client/test_data/test_update_no_sum_check/kcl.mod
pkg/client/test_data/test_update_no_sum_check/main.k
pkg/cmd/cmd_add.go
pkg/cmd/cmd_flags.go
pkg/cmd/cmd_run.go
pkg/cmd/cmd_update.go
pkg/opt/opt.go
pkg/package/package.go
test/e2e/test_suites/kpm/exec_inside_pkg/run_with_with_noargs_input/test_suite.stdout

add flag `--no_sum_check` to avoid the generation of 'kcl.mod.lock'
kpm add/kpm run/kpm update

feat: add flag '--no_sum_check' to support no kcl.mod.lock generation

---

pkg/version/version.go
pkg/version/version_test.go

chore: bump kpm version to 0.4.4

---

go.mod
go.sum
pkg/version/version.go
pkg/version/version_test.go

chore: bump kcl-go version and kpm version

---

pkg/version/version.go
pkg/version/version_test.go

chore: bump kpm version to 0.4.6

---

pkg/version/version.go
pkg/version/version_test.go

chore: bump kpm version to '0.4.7'

---

pkg/version/version.go
pkg/version/version_test.go

chore: bump kpm version to 0.5.0

---

aaa/kcl.mod
aaa/main.k

fix: rm useless dir

---

pkg/version/version.go
pkg/version/version_test.go

chore: bump kpm version to 0.7.0

---

pkg/client/client.go
pkg/package/modfile.go
pkg/package/package.go

pkg/package/modfile.go
pkg/package/modfile

remove unused arg from func

---

pkg/oci/oci.go

fixed https://github.com/kcl-lang/kcl/issues/1091
fix: fix the failure during push to harbor

fix: fix the failure during push to harbor

---

pkg/opt/opt.go
pkg/opt/opt_test.go
pkg/package/modfile.go

Add version option for mod init

---

pkg/api/kpm_pkg.go
pkg/api/kpm_pkg_test.go
pkg/api/test_data/test_get_mod_deps/kcl_pkg/kcl.mod
pkg/api/test_data/test_get_mod_deps/kcl_pkg/main.k
pkg/api/test_data/test_get_mod_deps/kcl_pkg/sub/main.k
pkg/api/test_data/test_get_mod_deps/kcl_pkg/sub/sub1/main.k
pkg/api/test_data/test_get_mod_deps/kcl_pkg/sub/sub1/main2.k

feat: add api to get the dependencies from kcl.mod

---

.gitignore
pkg/client/client.go
pkg/client/client_test.go
pkg/client/test_data/expected/kcl.mod
pkg/client/test_data/expected/kcl.reverse.mod
pkg/client/test_data/test_add_diff_version/no_sum_check/kcl.mod.expect
pkg/client/test_data/test_add_diff_version/with_sum_check/kcl.mod.expect
pkg/constants/constants.go
pkg/oci/oci.go
pkg/oci/oci_test.go
pkg/package/modfile.go
pkg/package/modfile_test.go
pkg/package/package.go
pkg/package/package_test.go
pkg/package/test_data/load_mod_file/kcl.mod
pkg/package/test_data/test_oci_url/marshal_0/kcl_mod_bk/kcl.mod
pkg/package/test_data/test_oci_url/marshal_1/expect.mod
pkg/package/test_data/test_oci_url/marshal_1/kcl.mod
pkg/package/test_data/test_oci_url/marshal_2/expect.mod
pkg/package/test_data/test_oci_url/marshal_2/kcl.mod
pkg/package/test_data/test_oci_url/marshal_3/expect.mod
pkg/package/test_data/test_oci_url/marshal_3/kcl.mod
pkg/package/test_data/test_oci_url/unmarshal_0/kcl.mod
pkg/package/test_data/test_oci_url/unmarshal_1/kcl.mod
pkg/package/toml.go
pkg/package/toml_test.go
pkg/utils/utils.go

feat: add marshall for oci url in kcl.mod

---

pkg/api/test_data/test_kpm_package/get_schema_ty/aaa/kcl.mod.lock
pkg/client/client.go
pkg/client/client_test.go
pkg/client/test_data/add_with_local_path/expect/pkg/kcl.mod.lock
pkg/client/test_data/add_with_local_path/init/pkg/kcl.mod.lock
pkg/client/test_data/test_cyclic_dependency/aaa/kcl.mod.lock
pkg/client/test_data/test_cyclic_dependency/bbb/kcl.mod.lock
pkg/cmd/cmd_add.go
pkg/cmd/cmd_run.go
pkg/package/modfile.go
pkg/package/package.go
test/e2e/test_suites/kpm/kpm_run/test_kpm_run_with_only_kcl_mod/test_suite.stdout
test/e2e/test_suites/kpm/kpm_update/test_update_with_diff_version/test_suite.stdout
test/e2e/test_suites/test_data/a_kcl_pkg_dep_one_pkg_4/kcl.mod.lock
test/e2e/test_suites/test_data/a_kcl_pkg_dep_one_pkg_5/kcl.mod.lock
test/e2e/test_suites/test_data/test_kpm_metadata/kcl.mod.lock
test/e2e/test_suites/test_data/test_kpm_metadata_duplication/kcl.mod.lock
test/e2e/test_suites/test_data/test_kpm_run_duplication_deps/kcl.mod.lock
test/e2e/test_suites/test_data/test_kpm_run_multi_local_path/pkg1/kcl.mod.lock
test/e2e/test_suites/test_data/test_kpm_run_multi_local_path/pkg2/kcl.mod.lock
test/e2e/test_suites/test_data/test_kpm_run_multi_local_path_0/pkg/pkg2/kcl.mod.lock
test/e2e/test_suites/test_data/test_kpm_run_multi_local_path_0/pkg1/kcl.mod.lock
test/e2e/test_suites/test_data/test_kpm_run_underline/test_with_line/kcl.mod.lock
test/e2e/test_suites/test_data/test_kpm_run_with_local_dep/kcl1/kcl.mod.lock
test/e2e/test_suites/test_data/test_kpm_run_with_only_kcl_mod/kcl.mod
test/e2e/test_suites/test_data/test_kpm_run_with_only_kcl_mod/main.k
test/e2e/test_suites/test_data/test_update_with_all/test_update/kcl.mod.lock

re https://github.com/kcl-lang/kcl/issues/1162

fix: turned off update indirect dependencies in kcl.mod

---

pkg/client/client.go
pkg/client/client_test.go

fix: fix logWriter missing in KpmClient

---

pkg/client/client.go
pkg/client/client_test.go

re https://github.com/kcl-lang/kcl/issues/1261

fix: dep ref symlink

---

pkg/utils/utils.go
pkg/utils/utils_test.go

fix: fix typo

---

pkg/client/client_test.go
pkg/client/test_data/add_with_default_dep/no_tag/kcl.mod.expect
pkg/client/test_data/add_with_default_dep/no_tag/kcl.mod.lock.expect
pkg/mvs/mvs_test.go

fix: bump helloworld version to fix ci

---

pkg/client/client_test.go
pkg/client/test_data/test_run_options/remote/expect_3.yaml
pkg/constants/constants.go
pkg/downloader/source.go
pkg/visitor/visitor.go

feat: make 'run' command supports ModSpec

---

pkg/visitor/test_data/test_visited_space/kcl.mod
pkg/visitor/test_data/test_visited_space/main.k
pkg/visitor/visitor.go
pkg/visitor/visitor_test.go

feat: add visitedSpace for visitor

---

pkg/client/client_test.go

refactor: refactor test case to recovery test environment

---

pkg/client/add.go
pkg/client/add_test.go
pkg/client/test_data/add_with_mod_spec/rename/kcl.mod.bk
pkg/client/test_data/add_with_mod_spec/rename/kcl.mod.expect
pkg/client/test_data/add_with_mod_spec/rename/kcl.mod.lock.expect
pkg/client/test_data/add_with_mod_spec/rename/main.k
pkg/downloader/source.go
pkg/downloader/toml.go
pkg/package/test_data/test_rename_pkg/kcl.mod
pkg/package/toml.go
pkg/package/toml_test.go

feat: supports rename when add dependency

---

pkg/client/add.go

fix: fix missing msg in api Add()

---

pkg/visitor/visitor.go

fix: update cache path after the latest version fetched

---

pkg/client/add.go
pkg/client/add_test.go
pkg/client/client_test.go
pkg/client/test_data/add_with_mod_spec/rename_spec_only/kcl.mod.bk
pkg/client/test_data/add_with_mod_spec/rename_spec_only/kcl.mod.expect
pkg/client/test_data/add_with_mod_spec/rename_spec_only/kcl.mod.lock.expect
pkg/client/test_data/add_with_mod_spec/rename_spec_only/main.k
pkg/client/test_data/add_with_mod_spec/spec_only/kcl.mod.bk
pkg/client/test_data/add_with_mod_spec/spec_only/kcl.mod.expect
pkg/client/test_data/add_with_mod_spec/spec_only/kcl.mod.lock.expect
pkg/client/test_data/add_with_mod_spec/spec_only_no_ver/kcl.mod.bk
pkg/client/test_data/add_with_mod_spec/spec_only_no_ver/kcl.mod.expect
pkg/client/test_data/add_with_mod_spec/spec_only_no_ver/kcl.mod.lock.expect
pkg/package/package.go

fix: fix mistakes in kcl.mod when adding deps with only ModSpec

---

pkg/client/client_test.go
pkg/client/pull.go
pkg/client/pull_test.go

fix: fill the default source info when pull with only ModSpec

---

pkg/client/client_test.go
pkg/client/issues_test.go
pkg/client/pull_test.go
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/add_with_commit/kcl.mod.bk
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/add_with_commit/kcl.mod.expect
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/add_with_commit/kcl.mod.lock.expect
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/add_with_commit/main.k
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/update_check_version/kcl.mod.bk
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/update_check_version/kcl.mod.expect
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/update_check_version/kcl.mod.lock.bk
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/update_check_version/kcl.mod.lock.expect
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/update_check_version/main.k
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/update_check_version_invalid/kcl.mod.bk
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/update_check_version_invalid/kcl.mod.expect
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/update_check_version_invalid/kcl.mod.lock.bk
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/update_check_version_invalid/kcl.mod.lock.expect
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/226/update_check_version_invalid/main.k
pkg/downloader/utils.go
pkg/utils/utils.go

fix: add a test cases for issue 266

---

pkg/client/deperated.go

re https://github.com/kcl-lang/kcl/issues/1775

fix: replace all method 'os.Rename' with method 'utils.MoveOrCopy'

---

pkg/client/client_test.go
pkg/client/test_data/test_new_storage/mod/kcl.mod
pkg/client/test_data/test_new_storage/mod/kcl.mod.lock
pkg/client/test_data/test_new_storage/mod/main.k
pkg/client/test_data/test_new_storage/mod_0/kcl.mod
pkg/client/test_data/test_new_storage/mod_0/kcl.mod.lock
pkg/client/test_data/test_new_storage/mod_0/main.k
pkg/client/test_data/test_new_storage/mod_1/kcl.mod
pkg/client/test_data/test_new_storage/mod_1/kcl.mod.lock
pkg/client/test_data/test_new_storage/mod_1/main.k
pkg/client/test_data/test_new_storage/mod_2/kcl.mod
pkg/client/test_data/test_new_storage/mod_2/kcl.mod.lock
pkg/client/test_data/test_new_storage/mod_2/main.k
pkg/client/test_data/test_new_storage/mod_3/kcl.mod
pkg/client/test_data/test_new_storage/mod_3/kcl.mod.lock
pkg/client/test_data/test_new_storage/mod_3/main.k
pkg/client/test_data/test_new_storage/mod_4/kcl.mod
pkg/client/test_data/test_new_storage/mod_4/kcl.mod.lock
pkg/client/test_data/test_new_storage/mod_4/main.k
pkg/client/test_data/test_new_storage/mod_5/kcl.mod
pkg/client/test_data/test_new_storage/mod_5/kcl.mod.lock
pkg/client/test_data/test_new_storage/mod_5/main.k
pkg/client/test_data/test_new_storage/mod_6/kcl.mod
pkg/client/test_data/test_new_storage/mod_6/kcl.mod.lock
pkg/client/test_data/test_new_storage/mod_6/main.k

test: add more test cases for the new storage

---

pkg/client/issues_test.go
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/605/README.md
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/605/pkg/kcl.mod
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/605/pkg/kcl.mod.lock
pkg/client/test_data/issues/github.com/kcl-lang/kpm/issues/605/pkg/main.k
pkg/client/test_data/test_data_add_deps/kcl.mod.lock
pkg/client/test_data/test_update_with_mvs/update_0/pkg/kcl.mod.lock.expect
pkg/client/test_data/test_update_with_mvs/update_1/pkg/kcl.mod.lock
pkg/client/update.go
pkg/package/modfile.go

fix: fix download slow when 'kcl run'

---

pkg/package/modfile.go
pkg/package/modfile_test.go
pkg/package/package.go
pkg/package/package_test.go
pkg/resolver/resolver.go

pkg/package/modfile.go
pkg/package/package.go

fix: Write to mod files only in case of a change

---

pkg/oci/oci.go
pkg/oci/oci_test.go

use https://github.com/kcl-lang/kpm/blob/main/pkg/client/login.go and https://github.com/kcl-lang/kpm/blob/main/pkg/client/logout.go  instead of it, I didn't mark it as outdated because we are in an early stage, so I think it can be deleted very easily

cleanup: remove unuse code of login
